name: skopeo-copy-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:latest
      options: --privileged
    steps:
    - name: Skopeo copy docker image
      uses: ixxeL-actions/skopeo-push@main
      with:
        src-img: 'ixxel/multi-tools-alpine:latest'
        dst-img: 'ixxel/multi-tools-alpine:latest'
        format: 'v2s2'
        src-transport: 'docker'
        dst-transport: 'docker'
        src-creds: 'ixxel:${{ secrets.DOCKER_IO_PWD }}'
        dst-creds: 'ixxel:${{ secrets.DOCKER_IO_PWD }}'
        src-tls: 'false'
        dst-tls: 'false'